[package]
name = "rust-youtube-serverless"
version = "0.1.0"
authors = ["Salvador Guzman <guzmansalv@gmail.com>"]
edition = "2018"

[[bin]]
name = "rust-youtube"
path = "src/main.rs"

[dependencies]
reqwest = "0.9.17"
serde = "1.0.91"
serde_json = "1.0.39"
handler = { path = "../function" }
